#!/usr/bin/python3
# Chase Pholdee-Kretschmar, cpho632, 208579690

import os
import sys 

def main(filename):
    root = os.path.join(os.getcwd(), ".versiondir")
    full_path = os.path.join(root, filename+'.1')
    if not os.path.isfile(full_path):
        print(f"{filename} does not exist!")
        return
    versions = []
    for file in os.listdir(root):
        if file[:-2] == filename:
            versions.append(file)
    versions.sort()
    for version in versions:
        print(version)

main(sys.argv[1])