#!/usr/bin/python3
# Chase Pholdee-Kretschmar, cpho632, 208579690

import os
import sys 

def main(filename):
    root = os.path.join(os.getcwd(), ".versiondir")
    latest_version = os.path.join(root, filename +'.1')
    for file in os.listdir(root):
        full_path = os.path.join(root, file)
        if file[:-2] == filename and full_path != latest_version:
            os.remove(full_path)
            print(f"Removed {file}")
    print("Successfuly removed all versions except current.")
main(sys.argv[1])